---
title: "negation"
author: "morgan moyer"
date: "10/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(philentropy)
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")
```

```{r read in the context data, include=FALSE, warning=FALSE, echo=FALSE}
context_root = read.csv("../../../03_experiment/data/normed.csv")
context_root$VerbLemma <- ""
context_root$Task <- "context"
context_root = context_root[,!(names(context_root) %in% c("X"))]

context_emb = read.csv("../../../04_experiment/data/normed.csv")
context_emb$Task <- "context"
context_emb = context_emb[,!(names(context_emb) %in% c("X"))]

c <- full_join(context_root,context_emb)
```

```{r read in the no context data, include=FALSE, warning=FALSE, echo=FALSE}

nocontext_root = read.csv("../../../05_experiment/data/normed_nocontext_root.csv")
nocontext_root$VerbLemma <- ""
nocontext_root$Task <- "nocontext"

nocontext_emb = read.csv("../../../06_experiment/data/normed_nocontext_embedded.csv")
nocontext_emb$Task <- "nocontext"
names(nocontext_root)
nc <- full_join(nocontext_root,nocontext_emb)
```

```{r bring in the negation coding}
corp = read.table("../../../../corpus/results/swbd.tab",sep="\t",header=T,quote="")
names(corp)
corp <- corp[,c("Item_ID","MatrixNegPresent","MatrixNegation","EmbeddedNegPresent","EmbeddedNegation")]
names(corp)[names(corp) == "Item_ID"] <- "tgrep_id"
table(d$MatrixNegPresent)
```

```{r combine everything together}
d <- full_join(nc,c)
d <- left_join(d,corp,by="tgrep_id")

# sanity check
nrow(context_root) +nrow(context_emb) + nrow(nocontext_root) + nrow(nocontext_emb)
nrow(d)
```

```{r recode the empty cells as 'no'}
d$MatrixNegPresent[d$MatrixNegPresent != "yes"] = "no"
```

# double check to make sure there aren't spurious instances of matrix negation
```{r matrix neg levels}
d$MatrixNegation <- as.factor(d$MatrixNegation)
levels(d$MatrixNegation)
```


```{r recode suprious matrix negation}
d$MatrixNegPresent[d$MatrixNegation == "another"] = "no"
d$MatrixNegPresent[d$MatrixNegation == "nothing"] = "no"
d$MatrixNegPresent[d$MatrixNegation == "whatnot"] = "no"

table(d$MatrixNegPresent)
```


# Let's graph overall
```{r agregate for graphing}
agr = d %>%
  # look only at embedded questions
  # filter(VerbLemma != "") %>% 
  group_by(MatrixNegPresent,paraphrase) %>%
  summarize(mean_rating = mean(normed_rating), CILow = ci.low(normed_rating), CIHigh = ci.high(normed_rating)) %>%
  mutate(YMin = mean_rating - CILow, YMax = mean_rating + CIHigh) %>%
  drop_na()
dodge = position_dodge(.9)
```

```{r graph}
ggplot(agr,aes(x=paraphrase, y=mean_rating, alpha=MatrixNegPresent, fill=paraphrase)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge, show.legend = FALSE) +
  # ggtitle("Mean rating for 'a' vs. 'every'") +
  xlab("paraphrase") +
  ylab("Mean rating") +
  guides(fill=FALSE) +
  guides(alpha=guide_legend(title="MatrixNegPresent")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    scale_fill_manual(values=cbPalette) +
    scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1))
# ggsave("../graphs/overall_negation.pdf",width=6,height=3)

```


## Look at mod x wh x matrix negation

```{r aggregate for modxwhxneg}
agr = d %>%
  group_by(paraphrase,Wh,ModalPresent,MatrixNegPresent) %>%
  summarize(mean_rating = mean(normed_rating), 
            CILow = ci.low(normed_rating), 
            CIHigh = ci.high(normed_rating)) %>%
  mutate(YMin = mean_rating - CILow, 
         YMax = mean_rating + CIHigh) %>%
  drop_na()
```

```{r graph factors overall}
# Re-Order the WH-levels by overall composition of DB
agr$Wh <- factor(agr$Wh, levels=c("what","how","where","why","who","when"))

ggplot(agr,aes(x=paraphrase, y=mean_rating, alpha=MatrixNegPresent, fill=paraphrase)) +
  geom_bar(position="dodge",stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_grid(Wh~ModalPresent) +
  xlab("Paraphrase") +
  ylab("Mean rating") +
  guides(fill=FALSE) +
  guides(alpha=guide_legend(title="MatrixNegPresent")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    scale_fill_manual(values=cbPalette) +
    scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1))

# ggsave("../graphs/modxwh_negation.pdf",width=3,height=6)
```


## Look at questionTYpe x matrix negation

```{r aggregate for qt x neg}
agr = d %>%
  group_by(paraphrase,QuestionType,MatrixNegPresent) %>%
  summarize(mean_rating = mean(normed_rating), 
            CILow = ci.low(normed_rating), 
            CIHigh = ci.high(normed_rating)) %>%
  mutate(YMin = mean_rating - CILow, 
         YMax = mean_rating + CIHigh) %>%
  drop_na()
```

```{r graph QT x Neg overall}
# # Re-Order the WH-levels by overall composition of DB
# agr$Wh <- factor(agr$Wh, levels=c("what","how","where","why","who","when"))

ggplot(agr,aes(x=paraphrase, y=mean_rating, alpha=MatrixNegPresent, fill=paraphrase)) +
  geom_bar(position="dodge",stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(~QuestionType) +
  xlab("Paraphrase") +
  ylab("Mean rating") +
  guides(fill=FALSE) +
  guides(alpha=guide_legend(title="MatrixNegPresent")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    scale_fill_manual(values=cbPalette) +
    scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1))

# ggsave("../graphs/modxwh_negation.pdf",width=3,height=6)
```


# Let's graph for just embedded questions
```{r agregate for graphing}
agr = d %>%
  # look only at embedded questions
  filter(VerbLemma != "") %>% 
  group_by(MatrixNegPresent,paraphrase) %>%
  summarize(mean_rating = mean(normed_rating), CILow = ci.low(normed_rating), CIHigh = ci.high(normed_rating)) %>%
  mutate(YMin = mean_rating - CILow, YMax = mean_rating + CIHigh) %>%
  drop_na()
dodge = position_dodge(.9)
```

```{r graph}
ggplot(agr,aes(x=paraphrase, y=mean_rating, alpha=MatrixNegPresent, fill=paraphrase)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge, show.legend = FALSE) +
  # ggtitle("Mean rating for 'a' vs. 'every'") +
  xlab("paraphrase") +
  ylab("Mean rating") +
  guides(fill=FALSE) +
  guides(alpha=guide_legend(title="MatrixNegPresent")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    scale_fill_manual(values=cbPalette) +
    scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1))

ggsave("../graphs/overall_negation_eq.pdf",width=3,height=6)

```


## Look at mod x wh x matrix negation

```{r aggregate for modxwhxneg}
agr = d %>%
  filter(VerbLemma != "") %>% 
  group_by(paraphrase,Wh,ModalPresent,MatrixNegPresent) %>%
  summarize(mean_rating = mean(normed_rating), 
            CILow = ci.low(normed_rating), 
            CIHigh = ci.high(normed_rating)) %>%
  mutate(YMin = mean_rating - CILow, 
         YMax = mean_rating + CIHigh) %>%
  drop_na()
```

```{r graph factors overall}
# Re-Order the WH-levels by overall composition of DB
agr$Wh <- factor(agr$Wh, levels=c("what","how","where","why","who","when"))

ggplot(agr,aes(x=paraphrase, y=mean_rating, alpha=MatrixNegPresent, fill=paraphrase)) +
  geom_bar(position="dodge",stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_grid(Wh~ModalPresent) +
  xlab("Paraphrase") +
  ylab("Mean rating") +
  guides(fill=FALSE) +
  guides(alpha=guide_legend(title="MatrixNegPresent")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    scale_fill_manual(values=cbPalette) +
    scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1))

ggsave("../graphs/modxwh_negation_eq.pdf",width=3,height=6)
```



```{r look at some specific verbs}
verb_count = d %>%
  group_by(VerbLemma,MatrixNegPresent) %>%
  summarize(count = n())
View(verb_count)

```

## Look at specific verbs
```{r aggregate and subset to specific verbs}
agr = d %>%
  # Most frequent
  filter(VerbLemma %in% c("know","see","wonder","understand","be","understand","surprise","predict","tell","figure","say","think","sure","learn","remember","forget")) %>%
  group_by(paraphrase,VerbLemma,MatrixNegPresent) %>%
  summarize(mean_rating = mean(normed_rating), CILow = ci.low(normed_rating), CIHigh = ci.high(normed_rating)) %>%
  mutate(YMin = mean_rating - CILow, YMax = mean_rating + CIHigh) %>%
  drop_na()

```

```{r graph}

ggplot(agr,aes(x=paraphrase, y=mean_rating, alpha=MatrixNegPresent, fill=paraphrase)) +
  geom_bar(position="dodge",stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(~VerbLemma) +
  xlab("Paraphrase") +
  ylab("Mean rating") +
  guides(fill=FALSE) +
  guides(alpha=guide_legend(title="MatrixNegPresent")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    scale_fill_manual(values=cbPalette) +
    scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1))

# ggsave("../graphs/matrixverbs_threotical.pdf",width=10,height=10)
```


# Know

```{r aggregate and subset to know}
agr = d %>%
  # Most frequent
  filter(VerbLemma == "know") %>%
  group_by(paraphrase,ModalPresent,MatrixNegPresent) %>%
  summarize(mean_rating = mean(normed_rating), CILow = ci.low(normed_rating), CIHigh = ci.high(normed_rating)) %>%
  mutate(YMin = mean_rating - CILow, YMax = mean_rating + CIHigh) %>%
  drop_na()

table(d$Wh,d$MatrixNegPresent)
```

```{r graph know}
# Re-Order the WH-levels by overall composition of DB
agr$Wh <- factor(agr$Wh, levels=c("what","how","where","why","who","when"))

ggplot(agr,aes(x=paraphrase, y=mean_rating, alpha=MatrixNegPresent, fill=paraphrase)) +
  geom_bar(position="dodge",stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(~ModalPresent) +
  xlab("Paraphrase") +
  ylab("Mean rating") +
  guides(fill=FALSE) +
  guides(alpha=guide_legend(title="MatrixNegPresent")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    scale_fill_manual(values=cbPalette) +
    scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1))

# ggsave("../graphs/matrixverbs_threotical.pdf",width=10,height=10)
```

# Forget

```{r aggregate and subset to forget}
agr = d %>%
  # Most frequent
  filter(VerbLemma == "forget") %>%
  group_by(paraphrase,Wh,MatrixNegPresent) %>%
  summarize(mean_rating = mean(normed_rating), CILow = ci.low(normed_rating), CIHigh = ci.high(normed_rating)) %>%
  mutate(YMin = mean_rating - CILow, YMax = mean_rating + CIHigh) %>%
  drop_na()

table(d$Wh,d$MatrixNegPresent)
```

```{r graph forget}
# Re-Order the WH-levels by overall composition of DB
agr$Wh <- factor(agr$Wh, levels=c("what","how","where","why","who","when"))

ggplot(agr,aes(x=paraphrase, y=mean_rating, alpha=MatrixNegPresent, fill=paraphrase)) +
  geom_bar(position="dodge",stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(~Wh) +
  xlab("Paraphrase") +
  ylab("Mean rating") +
  guides(fill=FALSE) +
  guides(alpha=guide_legend(title="MatrixNegPresent")) +
  theme(legend.key.size = unit(0.3, "cm"),
        legend.position = "top", # c(.5,1)
        legend.direction = "horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-5,-5),legend.spacing.y = unit(0.001, 'cm')) +
    scale_fill_manual(values=cbPalette) +
    scale_color_manual(values=cbPalette) +
    scale_alpha_discrete(range = c(.5,1))

# ggsave("../graphs/matrixverbs_threotical.pdf",width=10,height=10)
```

```{r take a look around}
d %>%
  filter((VerbLemma == "be")) %>% #
  group_by(tgrep_id,Sentence,paraphrase) %>%
  summarize(mean_rating = mean(normed_rating), sd = sd(normed_rating)) %>%
  # filter(mean_rating > .3) %>%
  View()

d %>%
  filter((VerbLemma == "know")) %>% #
  group_by(tgrep_id,Sentence,paraphrase) %>%
  summarize(mean_rating = mean(normed_rating), sd = sd(normed_rating)) %>%
  # filter(mean_rating > .3) %>%
  View()

```
